name: checker-cron

on:
  schedule:
    # 매일 KST 23:50:00에 실행 (UTC+9), 한국 타임존을 고려하여 23시에서 9시간을 빼줌
    - cron: 50 14 * * *
  workflow_dispatch:
    # 이 옵션을 설정해주어야 Github 웹에서 매뉴얼하게 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i -g yarn && yarn && yarn playwright install
      - name: Run checker
        run: yarn test
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
