name: checker-cron

on:
  schedule:
    # 평일은 KST 자정에 실행 (UTC+9)
    # 월, 화, 수, 목, 금 0시에 실행시키기 위해 일, 월, 화, 수, 목 3시에 실행
    - cron: 0 15 * * 0,1,2,3,4
    # 토 0시, 2시, 4시, 6시, 8시
    - cron: 0 15,17,19,21,23 * * 5
    # 토 10시, 12시, 14시, 16시, 18시, 20시, 22시, 일 0시, 2시, 4시, 6시, 8시
    - cron: 0 1,3,5,7,9,11,13,15,17,19,21,23 * * 6
    # 일 10시, 12시, 14시, 16시, 18시, 20시, 22시
    - cron: 0 1,3,5,7,9,11,13 * * 0

  workflow_dispatch:
    # 이 옵션을 설정해주어야 Github 웹에서 매뉴얼하게 실행 가능
    inputs:
      NOTICE_TO_USER:
        description: '결과 메시지를 사용자에게도 전송하기'
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    if:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm i -g yarn && yarn && yarn playwright install
      - name: Run checker
        run: yarn test
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          LLM_API_URL: ${{ secrets.LLM_API_URL }}
          NOTICE_TO_USER: ${{ github.event.inputs.NOTICE_TO_USER == 'true' || github.event_name == 'schedule' }}
